## PyTorch Neuron (torch-neuronx) Tracing API for Inference
- https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/api-reference-guide/inference/api-torch-neuronx-trace.html?highlight=torch_neuronx#torch_neuronx.trace

In [1]:
import torch
import torch_neuronx

def func(x, y):
    return 2 * x + y

example_inputs = torch.rand(3), torch.rand(3)
print("type of example_inputs: \n", type(example_inputs))
print("example_inputs: \n", example_inputs)
# Runs `func` with the provided inputs and records the tensor operations
# trace = torch.neuronx.trace(func, example_inputs)
trace = torch_neuronx.trace(func, example_inputs)

# `trace` can now be run with the TorchScript interpreter or saved
# and loaded in a Python-free environment
torch.jit.save(trace, 'func.pt')

# Executes on a NeuronCore
loaded = torch.jit.load('func.pt')
loaded(torch.rand(3), torch.rand(3))

type of example_inputs: 
 <class 'tuple'>
example_inputs: 
 (tensor([0.5112, 0.6984, 0.4634]), tensor([0.0254, 0.3582, 0.8700]))


03/07/2023 01:21:36 PM WARNING 96085 [py.warnings]: /home/ubuntu/aws_neuron_venv_pytorch/bin/neuronx-cc:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  sys.exit(main())

03/07/2023 01:21:38 PM WARNING 96085 [WalrusDriver]: 0% PSUM demand before spilling
03/07/2023 01:21:38 PM WARNING 96085 [WalrusDriver]: spilling from PSUM cost about 0 cycles
03/07/2023 01:21:38 PM WARNING 96085 [WalrusDriver]: 0% PSUM utilization after allocation
03/07/2023 01:21:38 PM WARNING 96085 [WalrusDriver]: spilling from SB cost about 0 cycles
03/07/2023 01:21:38 PM WARNING 96085 [WalrusDriver]: 0 bytes/partition (0%) successfully pinned
03/07/2023 01:21:38 PM WARNING 96085 [WalrusDriver]:

tensor([0.9044, 2.4038, 1.0988])

In [2]:
import torch
import torch_neuronx
import torch.nn as nn

class Model(nn.Module):

    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        return self.conv(x) + 1

model = Model()
model.eval()

example_inputs = torch.rand(1, 1, 3, 3)
print("type of example_inputs: \n", type(example_inputs))
print("example_inputs: \n", example_inputs)

# Traces the forward method and constructs a `ScriptModule`
trace = torch_neuronx.trace(model, example_inputs)
torch.jit.save(trace, 'model.pt')

# Executes on a NeuronCore
loaded = torch.jit.load('model.pt')
loaded(torch.rand(1, 1, 3, 3))

type of example_inputs: 
 <class 'torch.Tensor'>
example_inputs: 
 tensor([[[[0.3883, 0.1856, 0.2230],
          [0.5398, 0.5480, 0.5848],
          [0.1204, 0.8562, 0.4150]]]])


03/07/2023 01:21:42 PM WARNING 96125 [py.warnings]: /home/ubuntu/aws_neuron_venv_pytorch/bin/neuronx-cc:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  sys.exit(main())

03/07/2023 01:21:43 PM WARNING 96125 [LayoutBottleneck]: Connected component _convolution.21 has no matmult/reduce/batchnorm. Guessing layout. Considering putting on CPU.
03/07/2023 01:21:44 PM WARNING 96125 [WalrusDriver]: 12% PSUM demand before spilling
03/07/2023 01:21:44 PM WARNING 96125 [WalrusDriver]: spilling from PSUM cost about 0 cycles
03/07/2023 01:21:44 PM WARNING 96125 [WalrusDriver]: 12% PSUM utilization after allocation
03/07/2023 01:21:44 PM WARNING 96125 [WalrusDriver]: spilling fro

tensor([[[[0.8207]]]])

In [3]:
import torch
import torch_neuronx
import torch.nn as nn

class Model(nn.Module):

    def __init__(self):
        super().__init__()
        # self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x1, x2):
        return torch.cat((x1,x2),1)

model = Model()
model.eval()

example_inputs = torch.randn(2, 3) , torch.randn(2, 3)
print("type of example_inputs: \n", type(example_inputs))
print("len of example_inputs: \n", len(example_inputs))
print("example_inputs: \n", example_inputs)

# Traces the forward method and constructs a `ScriptModule`
trace = torch_neuronx.trace(model, example_inputs)
torch.jit.save(trace, 'model.pt')

# Executes on a NeuronCore
loaded = torch.jit.load('model.pt')
# loaded(example_inputs)
loaded(example_inputs[0],example_inputs[1] )

type of example_inputs: 
 <class 'tuple'>
len of example_inputs: 
 2
example_inputs: 
 (tensor([[ 1.1597, -0.2410, -0.8231],
        [ 0.3012,  2.5923,  0.1275]]), tensor([[-0.1748, -1.6743, -0.8576],
        [ 1.5608,  0.6385, -0.3045]]))


03/07/2023 01:21:45 PM WARNING 96153 [py.warnings]: /home/ubuntu/aws_neuron_venv_pytorch/bin/neuronx-cc:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  sys.exit(main())

03/07/2023 01:21:45 PM WARNING 96153 [LayoutBottleneck]: Connected component _concatenate.3 has no matmult/reduce/batchnorm. Guessing layout. Considering putting on CPU.
03/07/2023 01:21:47 PM WARNING 96153 [WalrusDriver]: 0% PSUM demand before spilling
03/07/2023 01:21:47 PM WARNING 96153 [WalrusDriver]: spilling from PSUM cost about 0 cycles
03/07/2023 01:21:47 PM WARNING 96153 [WalrusDriver]: 0% PSUM utilization after allocation
03/07/2023 01:21:47 PM WARNING 96153 [WalrusDriver]: spilling from S

tensor([[ 1.1597, -0.2410, -0.8231, -0.1748, -1.6743, -0.8576],
        [ 0.3012,  2.5923,  0.1275,  1.5608,  0.6385, -0.3045]])

In [4]:
import torch
import torch_neuronx
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        return self.conv(x) + 1

n = Net()
n.eval()

inputs = torch.rand(1, 1, 3, 3)
inputs_batch_8 = torch.rand(8, 1, 3, 3)

# Trace a neural network with input batch size of 1
neuron_net = torch_neuronx.trace(n, inputs)

# Enable the dynamic batch size feature so the traced network
# can consume variable sized batch inputs
neuron_net_dynamic_batch = torch_neuronx.dynamic_batch(neuron_net)

# Run inference on inputs with batch size of 8
# different than the batch size used in compilation (tracing)
ouput_batch_8 = neuron_net_dynamic_batch(inputs_batch_8)

03/07/2023 01:21:47 PM WARNING 96259 [py.warnings]: /home/ubuntu/aws_neuron_venv_pytorch/bin/neuronx-cc:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  sys.exit(main())

03/07/2023 01:21:47 PM WARNING 96259 [LayoutBottleneck]: Connected component _convolution.21 has no matmult/reduce/batchnorm. Guessing layout. Considering putting on CPU.
03/07/2023 01:21:49 PM WARNING 96259 [WalrusDriver]: 12% PSUM demand before spilling
03/07/2023 01:21:49 PM WARNING 96259 [WalrusDriver]: spilling from PSUM cost about 0 cycles
03/07/2023 01:21:49 PM WARNING 96259 [WalrusDriver]: 12% PSUM utilization after allocation
03/07/2023 01:21:49 PM WARNING 96259 [WalrusDriver]: spilling fro